apiVersion: v1
kind: Service
metadata:
  name: aihost-api-service
  namespace: aihost-mvp
spec:
  selector:
    app: aihost-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
